server:
  port: 8080
  servlet:
    context-path: /app
  tomcat:
    uri-encoding: UTF-8

web:
  upload-path: D:/temp/file/

spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}